In [1]:
import numpy as np
import pandas as pd

## Creating Array

In [18]:
a = np.random.rand(20,4)

In [19]:
a

array([[0.70525961, 0.29206708, 0.46993246, 0.71283672],
       [0.05167501, 0.33805195, 0.99640788, 0.46299262],
       [0.56471068, 0.87423599, 0.88838598, 0.17047868],
       [0.73369594, 0.16763548, 0.12956739, 0.6107671 ],
       [0.42630044, 0.68186019, 0.53631241, 0.6303985 ],
       [0.70532299, 0.32639372, 0.72234003, 0.16897891],
       [0.90256552, 0.76768775, 0.05957802, 0.00924293],
       [0.75134203, 0.94410323, 0.69050233, 0.37661122],
       [0.64094524, 0.19323713, 0.25304926, 0.98097205],
       [0.9319094 , 0.76553569, 0.57118829, 0.70739205],
       [0.54491223, 0.37859122, 0.93097653, 0.61431089],
       [0.87791591, 0.069718  , 0.06055669, 0.06180414],
       [0.05910058, 0.02347966, 0.25259033, 0.05751965],
       [0.84595895, 0.57508527, 0.40464816, 0.18963798],
       [0.67098641, 0.91793792, 0.99627053, 0.80391525],
       [0.72278475, 0.72433754, 0.43648405, 0.5346508 ],
       [0.34000362, 0.40319685, 0.28353965, 0.38963923],
       [0.56108065, 0.19712635,

## Converting Array into Pandas

In [20]:
df = pd. DataFrame(a, columns=['Column1', 'Column2','Column3','Column4']) 

## Applying some main and basic Pandas function

In [21]:
df

Column1   Column2   Column3   Column4
0   0.705260  0.292067  0.469932  0.712837
1   0.051675  0.338052  0.996408  0.462993
2   0.564711  0.874236  0.888386  0.170479
3   0.733696  0.167635  0.129567  0.610767
4   0.426300  0.681860  0.536312  0.630398
5   0.705323  0.326394  0.722340  0.168979
6   0.902566  0.767688  0.059578  0.009243
7   0.751342  0.944103  0.690502  0.376611
8   0.640945  0.193237  0.253049  0.980972
9   0.931909  0.765536  0.571188  0.707392
10  0.544912  0.378591  0.930977  0.614311
11  0.877916  0.069718  0.060557  0.061804
12  0.059101  0.023480  0.252590  0.057520
13  0.845959  0.575085  0.404648  0.189638
14  0.670986  0.917938  0.996271  0.803915
15  0.722785  0.724338  0.436484  0.534651
16  0.340004  0.403197  0.283540  0.389639
17  0.561081  0.197126  0.171480  0.372033
18  0.306492  0.005692  0.523021  0.872431
19  0.092682  0.653189  0.613185  0.226842

In [22]:
df.head()

Column1   Column2   Column3   Column4
0  0.705260  0.292067  0.469932  0.712837
1  0.051675  0.338052  0.996408  0.462993
2  0.564711  0.874236  0.888386  0.170479
3  0.733696  0.167635  0.129567  0.610767
4  0.426300  0.681860  0.536312  0.630398

In [23]:
df.tail()

Column1   Column2   Column3   Column4
15  0.722785  0.724338  0.436484  0.534651
16  0.340004  0.403197  0.283540  0.389639
17  0.561081  0.197126  0.171480  0.372033
18  0.306492  0.005692  0.523021  0.872431
19  0.092682  0.653189  0.613185  0.226842

In [24]:
df.isnull().sum()

Column1    0
Column2    0
Column3    0
Column4    0
dtype: int64

In [25]:
df.shape

(20, 4)

In [27]:
df.corr()

Column1   Column2   Column3   Column4
Column1  1.000000  0.300820 -0.261182  0.017818
Column2  0.300820  1.000000  0.443056 -0.065621
Column3 -0.261182  0.443056  1.000000  0.238002
Column4  0.017818 -0.065621  0.238002  1.000000

In [29]:
df.std()

Column1    0.276117
Column2    0.309383
Column3    0.303493
Column4    0.290407
dtype: float64

In [30]:
df.describe()

Column1    Column2    Column3    Column4
count  20.000000  20.000000  20.000000  20.000000
mean    0.571782   0.464958   0.499501   0.447673
std     0.276117   0.309383   0.303493   0.290407
min     0.051675   0.005692   0.059578   0.009243
25%     0.404726   0.196154   0.252935   0.184848
50%     0.655966   0.390894   0.496477   0.426316
75%     0.738107   0.734637   0.698462   0.649647
max     0.931909   0.944103   0.996408   0.980972

In [36]:
df

Column1   Column2   Column3   Column4
0   0.705260  0.292067  0.469932  0.712837
1   0.051675  0.338052  0.996408  0.462993
2   0.564711  0.874236  0.888386  0.170479
3   0.733696  0.167635  0.129567  0.610767
4   0.426300  0.681860  0.536312  0.630398
5   0.705323  0.326394  0.722340  0.168979
6   0.902566  0.767688  0.059578  0.009243
7   0.751342  0.944103  0.690502  0.376611
8   0.640945  0.193237  0.253049  0.980972
9   0.931909  0.765536  0.571188  0.707392
10  0.544912  0.378591  0.930977  0.614311
11  0.877916  0.069718  0.060557  0.061804
12  0.059101  0.023480  0.252590  0.057520
13  0.845959  0.575085  0.404648  0.189638
14  0.670986  0.917938  0.996271  0.803915
15  0.722785  0.724338  0.436484  0.534651
16  0.340004  0.403197  0.283540  0.389639
17  0.561081  0.197126  0.171480  0.372033
18  0.306492  0.005692  0.523021  0.872431
19  0.092682  0.653189  0.613185  0.226842

In [39]:
df.drop([1,2,3,4,5,6,7,8,9,10])

Column1   Column2   Column3   Column4
0   0.705260  0.292067  0.469932  0.712837
11  0.877916  0.069718  0.060557  0.061804
12  0.059101  0.023480  0.252590  0.057520
13  0.845959  0.575085  0.404648  0.189638
14  0.670986  0.917938  0.996271  0.803915
15  0.722785  0.724338  0.436484  0.534651
16  0.340004  0.403197  0.283540  0.389639
17  0.561081  0.197126  0.171480  0.372033
18  0.306492  0.005692  0.523021  0.872431
19  0.092682  0.653189  0.613185  0.226842

In [42]:
df.value_counts()

Column1   Column2   Column3   Column4 
0.051675  0.338052  0.996408  0.462993    1
0.059101  0.023480  0.252590  0.057520    1
0.902566  0.767688  0.059578  0.009243    1
0.877916  0.069718  0.060557  0.061804    1
0.845959  0.575085  0.404648  0.189638    1
0.751342  0.944103  0.690502  0.376611    1
0.733696  0.167635  0.129567  0.610767    1
0.722785  0.724338  0.436484  0.534651    1
0.705323  0.326394  0.722340  0.168979    1
0.705260  0.292067  0.469932  0.712837    1
0.670986  0.917938  0.996271  0.803915    1
0.640945  0.193237  0.253049  0.980972    1
0.564711  0.874236  0.888386  0.170479    1
0.561081  0.197126  0.171480  0.372033    1
0.544912  0.378591  0.930977  0.614311    1
0.426300  0.681860  0.536312  0.630398    1
0.340004  0.403197  0.283540  0.389639    1
0.306492  0.005692  0.523021  0.872431    1
0.092682  0.653189  0.613185  0.226842    1
0.931909  0.765536  0.571188  0.707392    1
dtype: int64

In [46]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
dtype: bool

## Numpy Functions

In [49]:
a = np.arange(101)

In [48]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [53]:
b = np.linspace(1,200)

In [54]:
b

array([  1.        ,   5.06122449,   9.12244898,  13.18367347,
        17.24489796,  21.30612245,  25.36734694,  29.42857143,
        33.48979592,  37.55102041,  41.6122449 ,  45.67346939,
        49.73469388,  53.79591837,  57.85714286,  61.91836735,
        65.97959184,  70.04081633,  74.10204082,  78.16326531,
        82.2244898 ,  86.28571429,  90.34693878,  94.40816327,
        98.46938776, 102.53061224, 106.59183673, 110.65306122,
       114.71428571, 118.7755102 , 122.83673469, 126.89795918,
       130.95918367, 135.02040816, 139.08163265, 143.14285714,
       147.20408163, 151.26530612, 155.32653061, 159.3877551 ,
       163.44897959, 167.51020408, 171.57142857, 175.63265306,
       179.69387755, 183.75510204, 187.81632653, 191.87755102,
       195.93877551, 200.        ])

In [60]:
c = np.zeros(30)

In [61]:
c

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [62]:
np.mean(b)

100.50000000000001

In [63]:
np.median(b)

100.5

In [65]:
np.var(b)

3434.7806122448983